const VACCINE_SCHEDULE = {
  0: [
    {
      name: "Viêm gan B lần 1",
      code: "HepB1",
      ageMonths: 0,
      required: true,
      definition: "Vaccine phòng chống virus viêm gan B",
      benefits: "Bảo vệ khỏi viêm gan B, ngăn ngừa xơ gan và ung thư gan",
      contraindications: "Dị ứng nặng với thành phần vaccine, sốt cao",
    },
    {
      name: "BCG",
      code: "BCG",
      ageMonths: 0,
      required: true,
      definition: "Vaccine phòng chống bệnh lao",
      benefits: "Bảo vệ khỏi các dạng lao nặng như lao màng não, lao hạch",
      contraindications: "Suy giảm miễn dịch, nhiễm HIV, đang mắc bệnh nặng",
    },
  ],
  1: [
    {
      name: "Viêm gan B lần 2",
      code: "HepB2",
      ageMonths: 1,
      required: true,
      definition: "Mũi tiêm thứ 2 vaccine phòng chống virus viêm gan B",
      benefits: "Tăng cường miễn dịch chống viêm gan B",
      contraindications: "Dị ứng nặng với thành phần vaccine, sốt cao",
    },
  ],
  2: [
    {
      name: "DPT-VGB-Hib lần 1",
      code: "DPT1",
      ageMonths: 2,
      required: true,
      definition:
        "Vaccine 5 trong 1 phòng bạch hầu, ho gà, uốn ván, viêm gan B, Hib",
      benefits:
        "Bảo vệ khỏi 5 bệnh nguy hiểm: bạch hầu, ho gà, uốn ván, viêm gan B, Hib",
      contraindications: "Dị ứng nặng, co giật không do sốt, bệnh não cấp tính",
    },
    {
      name: "Bại liệt uống lần 1",
      code: "OPV1",
      ageMonths: 2,
      required: true,
      definition: "Vaccine uống phòng bại liệt",
      benefits: "Bảo vệ khỏi virus bại liệt, ngăn ngừa tàn tật",
      contraindications: "Suy giảm miễn dịch, đang điều trị corticoid",
    },
  ],
  "2-12": [
    {
      name: "DPT-VGB-Hib lần 2",
      code: "DPT2",
      ageMonths: 3,
      required: true,
      definition: "Mũi tiêm thứ 2 vaccine 5 trong 1",
      benefits: "Tăng cường miễn dịch chống 5 bệnh nguy hiểm",
      contraindications: "Dị ứng nặng, co giật không do sốt, bệnh não cấp tính",
    },
    {
      name: "DPT-VGB-Hib lần 3",
      code: "DPT3",
      ageMonths: 4,
      required: true,
      definition: "Mũi tiêm thứ 3 vaccine 5 trong 1",
      benefits: "Hoàn thiện chu kì tiêm cơ bản chống 5 bệnh nguy hiểm",
      contraindications: "Dị ứng nặng, co giật không do sốt, bệnh não cấp tính",
    },

    {
      name: "Bại liệt uống lần 2",
      code: "OPV2",
      ageMonths: 3,
      required: true,
      definition: "Mũi uống thứ 2 vaccine phòng bại liệt",
      benefits: "Tăng cường miễn dịch chống bại liệt",
      contraindications: "Suy giảm miễn dịch, đang điều trị corticoid",
    },
    {
      name: "Bại liệt uống lần 3",
      code: "OPV3",
      ageMonths: 4,
      required: true,
      definition: "Mũi uống thứ 3 vaccine phòng bại liệt",
      benefits: "Hoàn thiện chu kì tiêm cơ bản chống bại liệt",
      contraindications: "Suy giảm miễn dịch, đang điều trị corticoid",
    },
    {
      name: "Sởi lần 1",
      code: "MCV1",
      ageMonths: 9,
      required: true,
      definition: "Vaccine phòng chống bệnh sởi",
      benefits: "Bảo vệ khỏi sởi, ngăn ngừa biến chứng như viêm phổi, viêm não",
      contraindications: "Suy giảm miễn dịch, dị ứng gelatin, đang có thai",
    },
    {
      name: "Viêm gan B lần 3",
      code: "HepB3",
      ageMonths: 6,
      required: true,
      definition: "Mũi tiêm cuối cùng vaccine phòng viêm gan B",
      benefits: "Hoàn thiện miễn dịch chống viêm gan B",
      contraindications: "Dị ứng nặng với thành phần vaccine, sốt cao",
    },
  ],
  "12-24": [
    {
      name: "Sởi - Rubella",
      code: "MR",
      ageMonths: 18,
      required: true,
      definition: "Vaccine phòng sởi và rubella",
      benefits: "Bảo vệ khỏi sởi và rubella, ngăn ngừa dị tật bẩm sinh",
      contraindications: "Suy giảm miễn dịch, dị ứng gelatin, đang có thai",
    },
    {
      name: "DPT nhắc lại",
      code: "DPT_B1",
      ageMonths: 18,
      required: true,
      definition: "Vaccine nhắc lại phòng bạch hầu, ho gà, uốn ván",
      benefits: "Duy trì miễn dịch chống bạch hầu, ho gà, uốn ván",
      contraindications: "Dị ứng nặng, co giật không do sốt",
    },
    {
      name: "Bại liệt nhắc lại",
      code: "OPV_B1",
      ageMonths: 18,
      required: true,
      definition: "Vaccine nhắc lại phòng bại liệt",
      benefits: "Duy trì miễn dịch chống bại liệt",
      contraindications: "Suy giảm miễn dịch, đang điều trị corticoid",
    },
    {
      name: "Viêm não Nhật Bản",
      code: "JE",
      ageMonths: 12,
      required: true,
      definition: "Vaccine phòng viêm não Nhật Bản",
      benefits: "Bảo vệ khỏi viêm não Nhật Bản do muỗi truyền",
      contraindications: "Dị ứng nặng với thành phần vaccine, sốt cao",
    },
  ],
  optional: [
    {
      name: "Rotavirus",
      code: "RV",
      ageMonths: 2,
      required: false,
      definition: "Vaccine phòng virus rotavirus",
      benefits: "Bảo vệ khỏi tiêu chảy nặng do rotavirus",
      contraindications: "Suy giảm miễn dịch, dị tật ruột nghiêm trọng",
    },
    {
      name: "Phế cầu",
      code: "PCV",
      ageMonths: 2,
      required: false,
      definition: "Vaccine phòng vi khuẩn phế cầu",
      benefits: "Bảo vệ khỏi viêm phổi, viêm màng não do phế cầu",
      contraindications: "Dị ứng nặng với thành phần vaccine",
    },
    {
      name: "Hib",
      code: "Hib",
      ageMonths: 2,
      required: false,
      definition: "Vaccine phòng vi khuẩn Haemophilus influenzae type b",
      benefits: "Bảo vệ khỏi viêm màng não, viêm phổi do Hib",
      contraindications: "Dị ứng nặng với thành phần vaccine",
    },
    {
      name: "Thủy đậu",
      code: "Varicella",
      ageMonths: 12,
      required: false,
      definition: "Vaccine phòng bệnh thủy đậu",
      benefits: "Bảo vệ khỏi thủy đậu và zona thần kinh",
      contraindications: "Suy giảm miễn dịch, dị ứng gelatin, đang có thai",
    },
  ],
};

export default VACCINE_SCHEDULE;
