dotenv.config();
import dotenv from "dotenv";

const API_GEMINI_KEY = process.env.GEMINI_API_KEY;
const GOOGLE_CLOUD_PROJECT = process.env.GOOGLE_CLOUD_PROJECT;
const GOOGLE_VERTEX_LOCATION = process.env.GOOGLE_VERTEX_LOCATION;
const GOOGLE_APPLICATION_CREDENTIALS =
  process.env.GOOGLE_APPLICATION_CREDENTIALS;
const CHROMA_SERVER_URL =
  process.env.CHROMA_SERVER_URL || "http://localhost:8000";
const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY;

export {
  API_OPEN_AI_KEY,
  API_GEMINI_KEY,
  GOOGLE_CLOUD_PROJECT,
  GOOGLE_VERTEX_LOCATION,
  GOOGLE_APPLICATION_CREDENTIALS,
  CHROMA_SERVER_URL,
  GOOGLE_API_KEY,
  OPENAI_EMBEDDING_MODEL,
};
