dotenv.config();
import dotenv from "dotenv";

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
const OPENAI_EMBEDDING_MODEL = "text-embedding-3-small";
const DEFAULT_TEMPERATURE = 0.7;
const DEFAULT_MAX_TOKEN = 1000;
const DEFAULT_K = 5;
const DEFAULT_SIMILARITY_THRESHOLD = 0.2;
const DEFAULT_MODEL = "gpt-4o-mini-2024-07-18";
const CONTEXT_HISTORY_LIMIT = 5;
export {
  OPENAI_API_KEY,
  OPENAI_EMBEDDING_MODEL,
  DEFAULT_MAX_TOKEN,
  DEFAULT_TEMPERATURE,
  DEFAULT_K,
  DEFAULT_MODEL,
  DEFAULT_SIMILARITY_THRESHOLD,
  CONTEXT_HISTORY_LIMIT,
};
